server:
  port: 8201

#mp log
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.54.2:33306/gameforu_dev?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  rabbitmq:
    host: 192.168.54.2
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED  #confirm if message sent to exchange successfully
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual   #consummer confirm manually

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    #包的日志级别
    org.springframework.web: DEBUG
  #自定义log信息
  #config: classpath:config/logback-spring.xml
#  pattern:
#    #控制台的日志输出格式
#    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
#    #文件的日志输出格式
#    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'
  file:
    #日志名称
    name: app.log
    #存储的路径
    path: ./log/
    #存储的最大值
    max-size: 50MB
    #保存时间
    max-history: 7