server:
  port: 8202
# remote process call： open feign
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:   # config timeout
        connectTimeout: 30000 # consummer to producter
        readTimeout: 50000  # service of producter
spring:
  main:
    allow-bean-definition-overriding: true #allow bean having the same name: override
  elasticsearch:
    rest:
      uris: http://192.168.0.172:9200 #elasticsearch address
#      uris: http://192.168.54.2:9200 #elasticsearch address
  rabbitmq: # rabbitmq: docker in linux
    host: 192.168.0.172
#    host: 192.168.54.2
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
  redis: #docker in linux
    host: 192.168.0.172
#    host: 192.168.54.2
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲