server:
  port: 8200

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-admin
          #lb: loadbalance
          uri: lb://service-admin
          predicates:
            - Path=/*/admin/**

        - id: service-search
          uri: lb://service-search
          predicates:
            - Path=/*/search/**

        - id: service-permission
          uri: lb://service-permission
          predicates:
            - Path=/*/permission/**

        - id: service-user
            uri: lb://service-user
            predicates:
              - Path=/*/user/**