server:
  port: 8203
# remote process call： open feign
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:   # config timeout
        connectTimeout: 30000 # consummer to producter
        readTimeout: 50000  # service of producter
spring:
  # 只要用到了数据库就要配置，即使service文件在其他位置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.172:33306/gameforu_dev?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.54.2:33306/gameforu_dev?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true #allow bean having the same name: override
  elasticsearch:
    rest:
      uris: http://192.168.0.172:9200 #elasticsearch address
#      uris: http://192.168.54.2:9200 #elasticsearch address
  rabbitmq: # rabbitmq: docker in linux
    host: 192.168.0.172
    #    host: 192.168.54.2
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
  redis: #docker in linux
    host: 192.168.0.172
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲